version: '3.1'

services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}

